In [1]:
import tensorflow as tf

##Стиль TF v1.x
g = tf.Graph()
with g.as_default():
    a = tf.constant(1, name='a')
    b = tf.constant(2, name='b')
    c = tf.constant(3, name='c')
    z = 2 * (a - b) + c
with tf.compat.v1.Session(graph=g) as sess:
    print('Результат: z =', sess.run(z))

2022-03-12 13:16:43.303640: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-03-12 13:16:43.303669: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.


Результат: z = 1


2022-03-12 13:16:45.003218: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2022-03-12 13:16:45.003247: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2022-03-12 13:16:45.003267: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (user-UX410UAR): /proc/driver/nvidia/version does not exist
2022-03-12 13:16:45.005554: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [2]:
## Стиль TF v2
a = tf.constant(1, name='a')
b = tf.constant(2, name='b')
c = tf.constant(3, name='c')
z = 2 * (a - b) + c
tf.print('Результат: z= ', z)

Результат: z=  1


In [3]:
##Стиль TF-vl.x
g = tf.Graph()
with g.as_default():
    a = tf.compat.v1.placeholder(shape=None, dtype=tf.int32, name='tf_a')
    b = tf.compat.v1.placeholder(shape=None, dtype=tf.int32, name='tf_b')
    c = tf.compat.v1.placeholder(shape=None, dtype=tf.int32, name='tf_c')
    z = 2 * (a - b) + c
with tf.compat.v1.Session(graph=g) as sess:
    feed_dict = {a: 1, b: 2, c: 3}
    print('Результат: z =', sess.run(z, feed_dict=feed_dict))

Результат: z = 1


In [4]:
## Стиль TF-v2
def compute_z(a, b, c):
    r1 = tf.subtract(a, b)
    r2 = tf.multiply(2, r1)
    z = tf.add(r2, c)
    return z


tf.print('Скалярные входные данные:', compute_z(1, 2, 3))
tf.print('Bxoдныe данные ранга 1:', compute_z([1], [2], [3]))
tf.print('Bxoдныe данные ранга 2:', compute_z([[1]], [[2]], [[3]]))

Скалярные входные данные: 1
Bxoдныe данные ранга 1: [1]
Bxoдныe данные ранга 2: [[1]]


In [5]:
@tf.function
def compute_z(a, b, c):
    r1 = tf.subtract(a, b)
    r2 = tf.multiply(2, r1)
    z = tf.add(r2, c)
    return z


tf.print('Скалярные входные данные:', compute_z(1, 2, 3))
tf.print('Bxoдныe данные ранга 1:', compute_z([1], [2], [3]))
tf.print('Bxoдныe данные ранга 2:', compute_z([[1]], [[2]], [[3]]))

Скалярные входные данные: 1
Bxoдныe данные ранга 1: [1]
Bxoдныe данные ранга 2: [[1]]


In [6]:
@tf.function(input_signature=(tf.TensorSpec(shape=[None], dtype=tf.int32),
                              tf.TensorSpec(shape=[None], dtype=tf.int32),
                              tf.TensorSpec(shape=[None], dtype=tf.int32),))
def compute_z(a, b, c):
    r1 = tf.subtract(a, b)
    r2 = tf.multiply(2, r1)
    z = tf.add(r2, c)
    return z


tf.print('Bxoдныe данные ранга 1:', compute_z([1], [2], [3]))
tf.print('Входные данные ранга 1:', compute_z([1, 2], [2, 4], [3, 6]))

# tf.print('Входные данные ранга О:', compute_z(1, 2, 3))
### приведет к ошибке
# tf.print('Bxoдныe данные ранга 2:', compute_z([[1], [2]], [[2], [4]], [[3], [6]]))
### приведет к ошибке

Bxoдныe данные ранга 1: [1]
Входные данные ранга 1: [1 2]


In [12]:
a = tf.Variable(initial_value=3.14, name='var_a')
print(a)
b = tf.Variable(initial_value=[1, 2, 3], name='var_b')
print(b)
c = tf.Variable(initial_value=[True, False], dtype=tf.bool)
print(c)
d = tf.Variable(initial_value=['abc'], dtype=tf.string)
print(d)

<tf.Variable 'var_a:0' shape=() dtype=float32, numpy=3.14>
<tf.Variable 'var_b:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3], dtype=int32)>
<tf.Variable 'Variable:0' shape=(2,) dtype=bool, numpy=array([ True, False])>
<tf.Variable 'Variable:0' shape=(1,) dtype=string, numpy=array([b'abc'], dtype=object)>


In [14]:
w = tf.Variable([1, 2, 3], trainable=False)
print(w.trainable)

False
<tf.Variable 'UnreadVariable' shape=(3,) dtype=int32, numpy=array([3, 1, 4], dtype=int32)>
tf.Tensor([5 0 6], shape=(3,), dtype=int32)


In [15]:
print(w.assign([3, 1, 4], read_value=True))

<tf.Variable 'UnreadVariable' shape=(3,) dtype=int32, numpy=array([3, 1, 4], dtype=int32)>


In [16]:
w.assign_add([2, -1, 2], read_value=False)
print(w.value())

tf.Tensor([5 0 6], shape=(3,), dtype=int32)


In [18]:
tf.random.set_seed(1)
init = tf.keras.initializers.GlorotNormal()
tf.print(init(shape=(3,)))

[-0.722795904 1.01456821 0.251808226]


In [19]:
v = tf.Variable(init(shape=(2, 3)))
tf.print(v)

[[0.28982234 -0.782292783 -0.0453658961]
 [0.960991383 -0.120003454 0.708528221]]


In [21]:
class MyModule(tf.Module):
    def __init__(self):
        init = tf.keras.initializers.GlorotNormal()
        self.wl = tf.Variable(init(shape=(2, 3)), trainable=True)
        self.w2 = tf.Variable(init(shape=(1, 2)), trainable=False)


m = MyModule()
print('Все переменные модуля:', [v.shape for v in m.variables])
print('Обучаемая переменная:', [v.shape for v in m.trainable_variables])

Все переменные модуля: [TensorShape([1, 2]), TensorShape([2, 3])]
Обучаемая переменная: [TensorShape([2, 3])]


In [23]:
@tf.function
def f(x):
    w = tf.Variable([1, 2, 3])


f([1])

ValueError: in user code:

    File "/tmp/ipykernel_24938/3134900839.py", line 3, in f  *
        w = tf.Variable([1, 2, 3])

    ValueError: tf.function only supports singleton tf.Variables created on the first call. Make sure the tf.Variable is only created once or created outside tf.function. See https://www.tensorflow.org/guide/function#creating_tfvariables for more information.


In [24]:
w = tf.Variable(tf.random.uniform((3, 3)))


@tf.function
def compute_z(x):
    return tf.matmul(w, x)


x = tf.constant([[1], [2], [3]], dtype=tf.float32)
tf.print(compute_z(x))

[[4.68231201]
 [3.49924636]
 [2.97944832]]


In [25]:
w = tf.Variable(1.0)
b = tf.Variable(0.5)
print(w.trainable, b.trainable)

True True


In [26]:
x = tf.convert_to_tensor([1.4])
y = tf.convert_to_tensor([2.1])
with tf.GradientTape() as tape:
    z = tf.add(tf.multiply(w, x), b)
    loss = tf.reduce_sum(tf.square(y - z))
dloss_dw = tape.gradient(loss, w)
tf.print('dL/dw: ', dloss_dw)

dL/dw:  -0.559999764


In [27]:
tf.print(2 * x * (w * x + b - y))

[-0.559999764]


In [28]:
with tf.GradientTape() as tape:
    tape.watch(x)
    z = tf.add(tf.multiply(w, x), b)
    loss = tf.reduce_sum(tf.square(y - z))
dloss_dx = tape.gradient(loss, x)
tf.print('dL/dx: ', dloss_dx)

dL/dx:  [-0.399999857]


In [31]:
with tf.GradientTape(persistent=True) as tape:
    z = tf.add(tf.multiply(w, x), b)
    loss = tf.reduce_sum(tf.square(y - z))
dloss_dw = tape.gradient(loss, w)
tf.print('dL/dw: ', dloss_dw)

dloss_db = tape.gradient(loss, b)
tf.print('dL/db: ', dloss_db)

dL/dw:  -0.559999764
dL/db:  -0.399999857


In [32]:
optimizer = tf.keras.optimizers.SGD()
optimizer.apply_gradients(zip([dloss_dw, dloss_db], [w, b]))
tf.print('Обновленный вес:', w)
tf.print('Обновленное смещение:', b)

Обновленный вес: 1.0056
Обновленное смещение: 0.504


In [33]:
model = tf.keras.Sequential()
model.add(tf.keras.layers.Dense(units=16, activation='relu'))
model.add(tf.keras.layers.Dense(units=32, activation='relu'))
# # позднее создание переменных
model.build(input_shape=(None, 4))
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 16)                80        
                                                                 
 dense_1 (Dense)             (None, 32)                544       
                                                                 
Total params: 624
Trainable params: 624
Non-trainable params: 0
_________________________________________________________________


In [37]:
## вывод переменных модели
for v in model.variables:
    print('{:20s}'.format(v.name), v.trainable, v.shape)

dense/kernel:0       True (4, 16)
dense/bias:0         True (16,)
dense_1/kernel:0     True (16, 32)
dense_1/bias:0       True (32,)


In [40]:
model = tf.keras.Sequential()
model.add(
    tf.keras.layers.Dense(
        units=16,
        activation=tf.keras.activations.relu,
        kernel_initializer=tf.keras.initializers.glorot_uniform(),
        bias_initializer=tf.keras.initializers.Constant(2.0)
    ))
model.add(
    tf.keras.layers.Dense(
        units=32,
        activation=tf.keras.activations.sigmoid,
        kernel_regularizer=tf.keras.regularizers.l1
    ))
model.compile(
    optimizer=tf.keras.optimizers.SGD(learning_rate=0.001),
    loss=tf.keras.losses.BinaryCrossentropy(),
    metrics=[tf.keras.metrics.Accuracy(),
             tf.keras.metrics.Precision(),
             tf.keras.metrics.Recall(), ])